# Generated by Django 5.1.3 on 2025-01-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patientprofile_blood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('not_sure', 'Not Sure')], max_length=8),
        ),
    ]
