# Generated by Django 5.1.3 on 2025-01-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_doctorprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_doctor',
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
